### ISSUE TITLE
Entity not available 

### ISSUE THREAD

**Issue by PitbullSwe** [TekniskSupport/home-assistant-skolmaten#10]
Hi
My Skolmat stopped worked this weekend. 
I get Entity not available 
![1BB59EF9-C00C-4394-A316-4532A8B5790B](https://user-images.githubusercontent.com/105519597/217647375-4d34e64e-ad5d-459d-9e6e-11c42f090ef4.jpeg)

I have tried to reinstall it and looked that the school link worked and it does.

**Comment by TekniskSupport** [comment]
Do you get anything in your logs?
sounds like it didn't even create the entity which should have been done during startup

**Comment by PitbullSwe** [comment]
I have deleted in the file editer and put it in again on a nother row, and now its working
