### ISSUE TITLE
Varje dag innehåller vilken vecka det är

### ISSUE THREAD

**Issue by Maltavius** [TekniskSupport/home-assistant-skolmaten#4]
![image](https://user-images.githubusercontent.com/10133945/139031101-5d9b9361-a20d-44ae-a7dc-8dc101ff2b9c.png)

Vecka 43 borde vara titeln för matsedeln och veckodagarna borde vara utan veckospecifikationen.

**Comment by Maltavius** [comment]
> Jag tror nog faktiskt att om du inte vill göra en fork och modifiera indatan
> 
> att intee använda listkortet utan bara göra ett markdownkort eller liknande istället; du kan tex. göra en templatesensor med infon i och bara skriva ut den rakt uppochned i ett kort
> 
> Här är ett exempel på hur en sådan sensor hade kunnat se ut
> 
> {% for item in state_attr('sensor.skolmaten_ankiborgskolan','entries')%} {{ strptime(item.date,'%a, %d %b %Y %H:%M:%S GMT').timestamp()|timestamp_custom('%Y-%m-%d', true) }} {{ item.day.split(' - ')[0] }} {{ item.food }} {% endfor %}

Tack, men jag lyckas inte förstå hur jag ska få det där att fungera.

**Comment by TekniskSupport** [comment]
i din ui-lovelace fil lägg till ett kort med följande:
(byt ut namnet på sensorn mot din)

```
- type: markdown
  content: |
    {% for item in state_attr('sensor.skolmaten_skolansnamn','entries')%} 
    {{ strptime(item.date,'%a, %d %b %Y %H:%M:%S GMT').timestamp()|timestamp_custom('%Y-%m-%d', true) }}
    {{ item.day.split(' - ')[0] }} 
    {{ item.food }}
    {% endfor %}
```
