### ISSUE TITLE
Lägga till via HACS-HA.

### ISSUE THREAD

**Issue by EmilDuberg** [TekniskSupport/home-assistant-skolmaten#5]
Får inte till intregrationen, jag har försökt manuellt.
Men det känns inte som om min kunskap räcker till riktigt. Och när jag försöker lägga till via hacs så får jag upp enl bild. Eller vad gör jag för fel? Mvh.
![Screenshot_20211121-191734_Home Assistant](https://user-images.githubusercontent.com/62031469/142774242-f4f94730-3287-4e5f-97ad-dfe2f86d3545.jpg)

**Comment by TekniskSupport** [comment]
According to the error message, you have already successfully added the repository to the store

**Comment by EmilDuberg** [comment]
Okey. But it isnt there. :( I have deleated My manual installation and tried also.

**Comment by TekniskSupport** [comment]
Not sure how to help you; if that is, it is probably an issue with HACS and not the integration itself.
It works fine for me
![image](https://user-images.githubusercontent.com/13868526/143684723-498a5d69-0918-46f2-9412-575dc5d194e7.png)

**Comment by EmilDuberg** [comment]
Okey, witch version do you have of HACS maybe i have to downgrade or something ?

**Comment by TekniskSupport** [comment]
Started from scratch (removed repository and integration)

Using this version:
![image](https://user-images.githubusercontent.com/13868526/143763333-2424a4f7-de6f-48bd-bb9f-e4eb7ffab6c0.png)


Adding custom repository:
![image](https://user-images.githubusercontent.com/13868526/143763391-e4a42a6d-98d9-4de5-9335-756dcbf0e6a7.png)

`https://github.com/TekniskSupport/home-assistant-skolmaten`

Integration now available:
![image](https://user-images.githubusercontent.com/13868526/143763412-169d5a37-8d6c-4f77-91f0-53bd4eb8ec86.png)

**Comment by EmilDuberg** [comment]
Oh, thanks for your time solving my problem, My SD card died yesterday, so i'm waiting for a new one. Hehe maybe that's a solution for my problem, a clean install
