### ISSUE TITLE
Förändringsförslag

### ISSUE THREAD

**Issue by jariivanoff** [TekniskSupport/home-assistant-skolmaten#8]
Finns det nån möjlighet att kunna bygga till så att man kan skicka in en offset eller liknande så att man kan bygga en template för att t.ex. fredag eftermiddag kunna visa nästa veckas lunchmeny? Hade varit en najs feature så man slipper se innevarande vecka på helgen.
Är ingen programmerare själv men såg i koden att ni använder offset=0. hade ju varit rikigt bra om man kunnat lägga offset som en parameter i sensorn eller liknande så att man med en template eller liknande kunnat känna av veckodag och/eller tid och sen slänga på en offset=1 istället från t.ex. fredag kl 14  fram till måndag.

**Comment by TekniskSupport** [comment]
Man behöver inte ens hämta per vecka, det var bara smidigt då veckomatsedel är ganska vedertaget
Det borde bli nästa vecka om man bara ändrar offset till 1 när man frågar efter veckor

Men det finns ett rssflöde som är per dag istället, och då borde det fungera så, det finns både offset och limit (exv. 10 dagar frammåt, eller -2 dagar +10

Skall se om jag får tid att sätta mig och knåpa med det

**Comment by jariivanoff** [comment]
Ok, ja, jag skulle vara glad att kunna köra per vecka. Jag vet att det finns en massa offsets man kan använda på Skolmaten.se,  har labbat en del med den, men detta är den bästa plugin:en för att presentera det. :-) Iofs så skulle rullande t.ex. 5 eller 7 dagar vara najs också men då tappar man ju den fina "Måndag till fredag" uppställningen och man måste börja ha koll på datum eller leta i listan.

**Comment by TekniskSupport** [comment]
Har släppt en uppdatering som tillåter dig att lägga på offset type och limit
det den egentligen gör är att ändra på frågan se dokumentationen för detaljer;
https://skolmaten.se/about/rss/smithskavagens-forskola/

Och hur parametrarna ser ut hittar du här:
https://github.com/TekniskSupport/home-assistant-skolmaten/blob/master/info.md
